Repository vexx32/PSKoans, pull requests merged in 2018-12, with the labels that each got.

#105 v0.42.2 - BulletProofing. I think.
  PSKoans/PSKoans.psm1
  PSKoans/Private/Invoke-Koan.ps1
  PSKoans/Private/Measure-Koan.ps1
  PSKoans/Public/Measure-Karma.ps1
Labels: Category-Module, PR-Needs Review

#104 Allow measure-karma -Contemplate to use code-insiders
  PSKoans/Public/Measure-Karma.ps1
Labels: Category-Module, PR-Awaiting-Author

#112 Change addition array example - fixes #111
  PSKoans/Koans/Foundations/AboutAssignmentAndArithmetic.Koans.ps1
Labels: Category-Koans, PR-Awaiting-Author, PR-Needs Review

#114 Remove unneeded wait periods
  PSKoans/Private/Invoke-Koan.ps1
  PSKoans/Private/Show-MeditationPrompt.ps1
  Tests/Functions/Private/Show-MeditationPrompt.Tests.ps1
Labels: Category-Module, PR-Needs Review

#115 Reformat Koans to report better error messages
  PSKoans/Koans/Cmdlets 1/AboutCompareObject.Koans.ps1
  PSKoans/Koans/Cmdlets 1/AboutDiscovery.Koans.ps1
  PSKoans/Koans/Cmdlets 1/AboutForEachObject.Koans.ps1
  PSKoans/Koans/Cmdlets 1/AboutGroupObject.Koans.ps1
  PSKoans/Koans/Cmdlets 1/AboutMeasureObject.Koans.ps1
  PSKoans/Koans/Cmdlets 1/AboutModules.Koans.ps1
  PSKoans/Koans/Cmdlets 1/AboutPSProviders.Koans.ps1
  PSKoans/Koans/Cmdlets 1/AboutSelectObject.Koans.ps1
  PSKoans/Koans/Cmdlets 1/AboutSortObject.Koans.ps1
  PSKoans/Koans/Cmdlets 1/AboutTeeObject.Koans.ps1
  PSKoans/Koans/Cmdlets 1/AboutWhereObject.Koans.ps1
  PSKoans/Koans/Constructs/AboutLists.Koans.ps1
  PSKoans/Koans/Constructs/AboutStringBuilder.Koans.ps1
  PSKoans/Koans/Foundations/AboutArrays.Koans.ps1
  PSKoans/Koans/Foundations/AboutAssertions.Koans.ps1
  PSKoans/Koans/Foundations/AboutAssignmentAndArithmetic.Koans.ps1
  PSKoans/Koans/Foundations/AboutComparison.Koans.ps1
  PSKoans/Koans/Foundations/AboutConditionals.Koans.ps1
  PSKoans/Koans/Foundations/AboutFunctionsAndScriptBlocks.Koans.ps1
  PSKoans/Koans/Foundations/AboutHashtables.Koans.ps1
  PSKoans/Koans/Foundations/AboutLoopsAndPipelines.Koans.ps1
  PSKoans/Koans/Foundations/AboutOrderOfOperations.Koans.ps1
  PSKoans/Koans/Foundations/AboutStringOperators.Koans.ps1
  PSKoans/Koans/Foundations/AboutStrings.Koans.ps1
  PSKoans/Koans/Foundations/AboutTypeOperators.Koans.ps1
  PSKoans/Koans/Foundations/AboutVariables.Koans.ps1
Labels: Category-Koans, PR-Needs Review

#118 Display additional progress bar for farthest topic reached
  PSKoans/Private/Show-MeditationPrompt.ps1
  PSKoans/Public/Measure-Karma.ps1
  Tests/Functions/Private/Show-MeditationPrompt.Tests.ps1
Labels: Category-Module, PR-Needs Review
