Repository vexx32/PSKoans, pull requests merged in 2018-07, with the labels that each got.

#10 About arrays.negative indexes
  Koans/01_Foundations/05_AboutArrays.Tests.ps1
Labels: enhancement

#14 Comment based help
  PSKoans.psm1
Labels: PR:UnderConsideration

#17 Fix proper confirmations and meditation prompts
  PSKoans.psm1
Labels: PR:Accepted

#18 Fixed a typo on Line 77 comment
  Koans/01_Foundations/02_AboutAssignment.Tests.ps1
Labels: PR:Accepted

#16 Started root module testing
  Tests/PSKoans.tests.ps1
Labels: PR:Accepted
