Repository vexx32/PSKoans, pull requests merged in 2018-10, with the labels that each got.

#69 Fruit for Vegetables
  PSKoans/Koans/Foundations/AboutHashtables.Koans.ps1
Labels: PR:Accepted

#67 Updates about type operators
  PSKoans/Koans/Foundations/AboutTypeOperators.Koans.ps1
Labels: PR:Accepted

#64 Changes ExpectedType to ExpectedMessage
  PSKoans/Koans/Foundations/AboutAssignmentAndArithmetic.Koans.ps1
Labels: Category:Koans, PR:Accepted

#63 Adds comment to indicate action is required
  PSKoans/Koans/Foundations/AboutArrays.Koans.ps1
Labels: Category:Koans, PR:Accepted

#71 Remove `rake` aliases and mentions to it in the prompts.
  PSKoans/PSKoans.psd1
  PSKoans/Private/Write-MeditationPrompt.ps1
  PSKoans/Public/Measure-Karma.ps1
Labels: Category:ModuleFunctions, PR:Accepted
